apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: {{ .Values.name }}
    run: {{ .Values.name }}