    
pr:
  branches:
    include:
    - master

variables:
  helmVersion: '2.14.1'
  kubectlVersion: v1.12.1
  nodeVersionSpec: 10.x

stages:
  - template: ../../../../pipeline-template.yml
    parameters:

      linuxAgentPool: 'ubuntu-latest'
      windowsAgentPool: 'windows-latest'
      buildType: 'nodejs'
      projectName: 'mydrive-user'
      initSteps: []
      docker: true
      helm: true
      imageName: 'mydrive-user'
      helmCharts: charts
      codeRootDir: docs/demo/nodejs
      deployType: 'helm-native'
      PR: {
        enabled: true,
        gate: true,
        credscan: true,
        codescan: true,
        vulnerabilitiesscan: true
      }
      CI: {
        enabled: false
      }
      AUTOMATION: {
        enabled: false
      }
      FUNCTIONAL: {
        enabled: false
      }
      NONFUNCTIONAL: {
        enabled: false
      }